/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acchiappatalpa;

/**
 *
 * @author trivella.augusto
 */
public class TalpaJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TalpaJFrame.class.getName());

    /**
     * Creates new form TalpaJFrame
     */
    public TalpaJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buca1 = new javax.swing.JButton();
        buca2 = new javax.swing.JButton();
        buca3 = new javax.swing.JButton();
        buca4 = new javax.swing.JButton();
        buca5 = new javax.swing.JButton();
        buca6 = new javax.swing.JButton();
        buca8 = new javax.swing.JButton();
        buca7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buca1.setBackground(new java.awt.Color(0, 204, 51));
        buca1.setForeground(new java.awt.Color(0, 255, 51));
        buca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buca1ActionPerformed(evt);
            }
        });

        buca2.setBackground(new java.awt.Color(0, 204, 51));
        buca2.setActionCommand("");
        buca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buca2ActionPerformed(evt);
            }
        });

        buca3.setBackground(new java.awt.Color(0, 204, 51));

        buca4.setBackground(new java.awt.Color(0, 204, 51));

        buca5.setBackground(new java.awt.Color(0, 204, 51));
        buca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buca5ActionPerformed(evt);
            }
        });

        buca6.setBackground(new java.awt.Color(0, 204, 51));
        buca6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buca6ActionPerformed(evt);
            }
        });

        buca8.setBackground(new java.awt.Color(0, 204, 51));

        buca7.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(buca4)
                        .addGap(104, 104, 104)
                        .addComponent(buca5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buca1)
                                .addGap(87, 87, 87)
                                .addComponent(buca2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buca6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buca7)))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buca3)
                            .addComponent(buca8))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buca1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buca2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buca3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buca4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buca5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buca6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buca8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buca7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buca1ActionPerformed

    private void buca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buca2ActionPerformed

    private void buca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buca5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buca5ActionPerformed

    private void buca6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buca6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buca6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TalpaJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buca1;
    private javax.swing.JButton buca2;
    private javax.swing.JButton buca3;
    private javax.swing.JButton buca4;
    private javax.swing.JButton buca5;
    private javax.swing.JButton buca6;
    private javax.swing.JButton buca7;
    private javax.swing.JButton buca8;
    // End of variables declaration//GEN-END:variables
}
